### ISSUE TITLE
Frontend for main app view

### ISSUE THREAD

**Issue by MIZINCHIK** [ogniloud/MADR#10]
Main app view after signing in. Decks are shown as cards with brief description. Placeholders for heatmap and other elements. The layout needs discussion.

**Comment by MIZINCHIK** [comment]
The main page shows a little bit of the user information at the top. The center of the screen is dedicated for the decks. Each deck is represented by a card with a brief description. The layout should include a place for heatmap (daily streak), total amount of cards that user has added, total words learned, total amount of decks.

**Comment by pelageech** [comment]
Создать новую ветку

**Comment by pelageech** [comment]
https://github.com/ogniloud/MADR/pull/36
