### ISSUE TITLE
Bussiness logic of Sign up/in

### ISSUE THREAD

**Issue by pelageech** [ogniloud/MADR#2]
Срок 9:00 2.11

**Comment by peyuaa** [comment]
**Sign up request example**
POST /api/signup HTTP/1.1
Content-Type: application/json; charset=utf-8
Host: 
Connection: close
User-Agent: RapidAPI/4.2.0 (Macintosh; OS X/13.6.0) GCDHTTPRequest
Content-Length: 83

{"username":"newuser","email":"newuser@example.com","password":"securepassword123"}


**In the case of a successful sign-up:**
{
  "status": "success",
  "message": "Your account has been created successfully.",
  "user": {
    "id": 123,
    "username": "newuser",
    "email": "newuser@example.com"
  }
}

**Error response:**
{
  "status": "error",
  "message": "Invalid email address. Please provide a valid email.",
  "errors": {
    "email": "Invalid email address format."
  }
}

**Comment by peyuaa** [comment]
**Sign in request**

```
POST /api/login HTTP/1.1
Host: example.com
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "securepassword123"
}
```

**Success Response (HTTP 200 OK):**
```
{
  "status": "success",
  "message": "Login successful.",
  "user": {
    "id": 123,
    "username": "user123",
    "email": "user@example.com",
    // Additional user information
  }
}
```

**Error Response (HTTP 401 Unauthorized or 4xx for Authentication Errors or 5xx or whatever):**
```
{
  "status": "error",
  "message": "Authentication failed. Please check your email and password.",
  "errors": {
    "password": "Invalid password."
  }
}
```

**Comment by pelageech** [comment]
Срок 9:00 2.11
